app = "pa-copilot-api-dan-fellner"
primary_region = "iad"

[build]
  # Uses your Dockerfile automatically

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

# Run DB migrations on each deploy (requires alembic in your image)
[deploy]
  release_command = "alembic upgrade head"