"""add provider fields to prior_auth_requests

Revision ID: 657a3f314380
Revises: b0e18a9bcd41
Create Date: 2025-09-02 23:32:47.421043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657a3f314380'
down_revision: Union[str, None] = 'b0e18a9bcd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_coverages_external_id', 'coverages', type_='unique')
    op.drop_index('ix_coverages_external_id', table_name='coverages')
    op.create_index(op.f('ix_coverages_external_id'), 'coverages', ['external_id'], unique=True)
    op.drop_constraint('uq_patients_external_id', 'patients', type_='unique')
    op.drop_index('ix_patients_external_id', table_name='patients')
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=True)
    op.add_column('prior_auth_requests', sa.Column('provider_name', sa.String(length=255), nullable=True))
    op.add_column('prior_auth_requests', sa.Column('provider_npi', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prior_auth_requests', 'provider_npi')
    op.drop_column('prior_auth_requests', 'provider_name')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.create_index('ix_patients_external_id', 'patients', ['external_id'], unique=False)
    op.create_unique_constraint('uq_patients_external_id', 'patients', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_coverages_external_id'), table_name='coverages')
    op.create_index('ix_coverages_external_id', 'coverages', ['external_id'], unique=False)
    op.create_unique_constraint('uq_coverages_external_id', 'coverages', ['external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
