"""add coverage and prior_auth_requests

Revision ID: 74d4d87b4c30
Revises: d393fe38a158
Create Date: 2025-08-14 00:10:14.417595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d4d87b4c30'
down_revision: Union[str, None] = 'd393fe38a158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=False),
    sa.Column('payer', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prior_auth_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('coverage_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('diagnosis_codes', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('requested', 'pending', 'approved', 'denied', 'not_required', name='priorauthstatus'), nullable=False),
    sa.Column('disposition', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverages.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prior_auth_requests')
    op.drop_table('coverages')
    # ### end Alembic commands ###
