"""add document_references

Revision ID: 7b84e83c0a80
Revises: 74d4d87b4c30
Create Date: 2025-08-15 10:12:33.400699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b84e83c0a80'
down_revision: Union[str, None] = '74d4d87b4c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('pa_request_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pa_request_id'], ['prior_auth_requests.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_references')
    # ### end Alembic commands ###
