"""add provider fields to prior_auth_requests

Revision ID: c1d2e3f4g5h6
Revises: 7b84e83c0a80
Create Date: 2025-01-03 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = '7b84e83c0a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prior_auth_requests', sa.Column('provider_name', sa.String(length=255), nullable=True))
    op.add_column('prior_auth_requests', sa.Column('provider_npi', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prior_auth_requests', 'provider_npi')
    op.drop_column('prior_auth_requests', 'provider_name')
    # ### end Alembic commands ###
